services:
  ewm-service:
    container_name: ewm-service
    build:
      ewm-service
    ports:
      - "8080:8080"
    depends_on:
      ewm-db:
        condition: service_healthy
      stats-server:
        condition: service_started

    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-service
      - SPRING_DATASOURCE_USERNAME=mira
      - SPRING_DATASOURCE_PASSWORD=password
      - STATS_SERVICE_URL=http://stats-server:9090


  ewm-db:
    container_name: ewm-service-db
    image: postgres:16.3-alpine
    ports:
      - "5440:5432"
    environment:
      - POSTGRES_DB=ewm-service
      - POSTGRES_USER=mira
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  stats-server:
    container_name: ewm-stats-server
    build:
      ewm-stats/stats-service
    ports:
      - "9090:9090"
    depends_on:
      stats-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats
      - SPRING_DATASOURCE_USERNAME=mira
      - SPRING_DATASOURCE_PASSWORD=password

  stats-db:
    container_name: ewm-stats-db
    image: postgres:16.3-alpine
    ports:
      - "5450:5432"
    environment:
      - POSTGRES_DB=ewm-stats
      - POSTGRES_USER=mira
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
