CREATE TABLE IF NOT EXISTS hits (
    id BIGINT GENERATED ALWAYS AS IDENTITY,
    app CHARACTER VARYING (500) NOT NULL,
    uri CHARACTER VARYING (500) NOT NULL,
    user_ip CHARACTER VARYING (500) NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_hits
        PRIMARY KEY (id)
);